package org.opentaps.domain.base.entities;

/*
* Copyright (c) 2008 - 2009 Open Source Strategies, Inc.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the Honest Public License.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* Honest Public License for more details.
*
* You should have received a copy of the Honest Public License
* along with this program; if not, write to Funambol,
* 643 Bair Island Road, Suite 305 - Redwood City, CA 94063, USA
*/

// DO NOT EDIT THIS FILE!  THIS IS AUTO GENERATED AND WILL GET WRITTEN OVER PERIODICALLY WHEN THE DATA MODEL CHANGES
// EXTEND THIS CLASS INSTEAD.

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import javolution.util.FastMap;

import org.opentaps.foundation.entity.Entity;
import org.opentaps.foundation.entity.EntityFieldInterface;
import org.opentaps.foundation.repository.RepositoryException;
import org.opentaps.foundation.repository.RepositoryInterface;
import javax.persistence.*;
import java.lang.String;
import java.sql.Timestamp;

/**
 * Auto generated base entity AcctgTagEnumType.
 */
@javax.persistence.Entity
@Table(name="ACCTG_TAG_ENUM_TYPE")
@IdClass(AcctgTagEnumTypePk.class)
public class AcctgTagEnumType extends Entity {
static {
java.util.Map<String, String> fields = new java.util.HashMap<String, String>();
        fields.put("organizationPartyId", "ORGANIZATION_PARTY_ID");
        fields.put("acctgTagUsageTypeId", "ACCTG_TAG_USAGE_TYPE_ID");
        fields.put("enumTypeId1", "ENUM_TYPE_ID1");
        fields.put("enumTypeId2", "ENUM_TYPE_ID2");
        fields.put("enumTypeId3", "ENUM_TYPE_ID3");
        fields.put("enumTypeId4", "ENUM_TYPE_ID4");
        fields.put("enumTypeId5", "ENUM_TYPE_ID5");
        fields.put("enumTypeId6", "ENUM_TYPE_ID6");
        fields.put("enumTypeId7", "ENUM_TYPE_ID7");
        fields.put("enumTypeId8", "ENUM_TYPE_ID8");
        fields.put("enumTypeId9", "ENUM_TYPE_ID9");
        fields.put("enumTypeId10", "ENUM_TYPE_ID10");
        fields.put("isTagEnum1Required", "IS_TAG_ENUM1_REQUIRED");
        fields.put("isTagEnum2Required", "IS_TAG_ENUM2_REQUIRED");
        fields.put("isTagEnum3Required", "IS_TAG_ENUM3_REQUIRED");
        fields.put("isTagEnum4Required", "IS_TAG_ENUM4_REQUIRED");
        fields.put("isTagEnum5Required", "IS_TAG_ENUM5_REQUIRED");
        fields.put("isTagEnum6Required", "IS_TAG_ENUM6_REQUIRED");
        fields.put("isTagEnum7Required", "IS_TAG_ENUM7_REQUIRED");
        fields.put("isTagEnum8Required", "IS_TAG_ENUM8_REQUIRED");
        fields.put("isTagEnum9Required", "IS_TAG_ENUM9_REQUIRED");
        fields.put("isTagEnum10Required", "IS_TAG_ENUM10_REQUIRED");
        fields.put("lastUpdatedStamp", "LAST_UPDATED_STAMP");
        fields.put("lastUpdatedTxStamp", "LAST_UPDATED_TX_STAMP");
        fields.put("createdStamp", "CREATED_STAMP");
        fields.put("createdTxStamp", "CREATED_TX_STAMP");
fieldMapColumns.put("AcctgTagEnumType", fields);
}
  public static enum Fields implements EntityFieldInterface<AcctgTagEnumType> {
    organizationPartyId("organizationPartyId"),
    acctgTagUsageTypeId("acctgTagUsageTypeId"),
    enumTypeId1("enumTypeId1"),
    enumTypeId2("enumTypeId2"),
    enumTypeId3("enumTypeId3"),
    enumTypeId4("enumTypeId4"),
    enumTypeId5("enumTypeId5"),
    enumTypeId6("enumTypeId6"),
    enumTypeId7("enumTypeId7"),
    enumTypeId8("enumTypeId8"),
    enumTypeId9("enumTypeId9"),
    enumTypeId10("enumTypeId10"),
    isTagEnum1Required("isTagEnum1Required"),
    isTagEnum2Required("isTagEnum2Required"),
    isTagEnum3Required("isTagEnum3Required"),
    isTagEnum4Required("isTagEnum4Required"),
    isTagEnum5Required("isTagEnum5Required"),
    isTagEnum6Required("isTagEnum6Required"),
    isTagEnum7Required("isTagEnum7Required"),
    isTagEnum8Required("isTagEnum8Required"),
    isTagEnum9Required("isTagEnum9Required"),
    isTagEnum10Required("isTagEnum10Required"),
    lastUpdatedStamp("lastUpdatedStamp"),
    lastUpdatedTxStamp("lastUpdatedTxStamp"),
    createdStamp("createdStamp"),
    createdTxStamp("createdTxStamp");
    private final String fieldName;
    private Fields(String name) { fieldName = name; }
    /** {@inheritDoc} */
    public String getName() { return fieldName; }
    /** {@inheritDoc} */
    public String asc() { return fieldName + " ASC"; }
    /** {@inheritDoc} */
    public String desc() { return fieldName + " DESC"; }
  }

    @Id
    
    @Column(name="ORGANIZATION_PARTY_ID")
    private String organizationPartyId;
    @Id
    
    @Column(name="ACCTG_TAG_USAGE_TYPE_ID")
    private String acctgTagUsageTypeId;
    
    @Column(name="ENUM_TYPE_ID1")
    private String enumTypeId1;
    
    @Column(name="ENUM_TYPE_ID2")
    private String enumTypeId2;
    
    @Column(name="ENUM_TYPE_ID3")
    private String enumTypeId3;
    
    @Column(name="ENUM_TYPE_ID4")
    private String enumTypeId4;
    
    @Column(name="ENUM_TYPE_ID5")
    private String enumTypeId5;
    
    @Column(name="ENUM_TYPE_ID6")
    private String enumTypeId6;
    
    @Column(name="ENUM_TYPE_ID7")
    private String enumTypeId7;
    
    @Column(name="ENUM_TYPE_ID8")
    private String enumTypeId8;
    
    @Column(name="ENUM_TYPE_ID9")
    private String enumTypeId9;
    
    @Column(name="ENUM_TYPE_ID10")
    private String enumTypeId10;
    
    @Column(name="IS_TAG_ENUM1_REQUIRED")
    private String isTagEnum1Required;
    
    @Column(name="IS_TAG_ENUM2_REQUIRED")
    private String isTagEnum2Required;
    
    @Column(name="IS_TAG_ENUM3_REQUIRED")
    private String isTagEnum3Required;
    
    @Column(name="IS_TAG_ENUM4_REQUIRED")
    private String isTagEnum4Required;
    
    @Column(name="IS_TAG_ENUM5_REQUIRED")
    private String isTagEnum5Required;
    
    @Column(name="IS_TAG_ENUM6_REQUIRED")
    private String isTagEnum6Required;
    
    @Column(name="IS_TAG_ENUM7_REQUIRED")
    private String isTagEnum7Required;
    
    @Column(name="IS_TAG_ENUM8_REQUIRED")
    private String isTagEnum8Required;
    
    @Column(name="IS_TAG_ENUM9_REQUIRED")
    private String isTagEnum9Required;
    
    @Column(name="IS_TAG_ENUM10_REQUIRED")
    private String isTagEnum10Required;
    
    @Column(name="LAST_UPDATED_STAMP")
    private Timestamp lastUpdatedStamp;
    
    @Column(name="LAST_UPDATED_TX_STAMP")
    private Timestamp lastUpdatedTxStamp;
    
    @Column(name="CREATED_STAMP")
    private Timestamp createdStamp;
    
    @Column(name="CREATED_TX_STAMP")
    private Timestamp createdTxStamp;
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
    @JoinColumn(name="ORGANIZATION_PARTY_ID", insertable=false, updatable=false)
    @org.hibernate.annotations.Generated(
        org.hibernate.annotations.GenerationTime.ALWAYS
    )
    private Party party = null;
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
    @JoinColumn(name="ACCTG_TAG_USAGE_TYPE_ID", insertable=false, updatable=false)
    @org.hibernate.annotations.Generated(
        org.hibernate.annotations.GenerationTime.ALWAYS
    )
    private AcctgTagUsageType acctgTagUsageType = null;

  /**
   * Default constructor.
   */
  public AcctgTagEnumType() {
      super();
      this.baseEntityName = "AcctgTagEnumType";
      this.isView = false;
      
      this.primaryKeyNames = new ArrayList<String>();
      this.primaryKeyNames.add("organizationPartyId");this.primaryKeyNames.add("acctgTagUsageTypeId");
  }

  /**
   * Constructor with a repository.
   * @param repository a <code>RepositoryInterface</code> value
   */
  public AcctgTagEnumType(RepositoryInterface repository) {
      this();
      initRepository(repository);
  }

    /**
     * Auto generated value setter.
     * @param organizationPartyId the organizationPartyId to set
     */
    public void setOrganizationPartyId(String organizationPartyId) {
        this.organizationPartyId = organizationPartyId;
    }
    /**
     * Auto generated value setter.
     * @param acctgTagUsageTypeId the acctgTagUsageTypeId to set
     */
    public void setAcctgTagUsageTypeId(String acctgTagUsageTypeId) {
        this.acctgTagUsageTypeId = acctgTagUsageTypeId;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId1 the enumTypeId1 to set
     */
    public void setEnumTypeId1(String enumTypeId1) {
        this.enumTypeId1 = enumTypeId1;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId2 the enumTypeId2 to set
     */
    public void setEnumTypeId2(String enumTypeId2) {
        this.enumTypeId2 = enumTypeId2;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId3 the enumTypeId3 to set
     */
    public void setEnumTypeId3(String enumTypeId3) {
        this.enumTypeId3 = enumTypeId3;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId4 the enumTypeId4 to set
     */
    public void setEnumTypeId4(String enumTypeId4) {
        this.enumTypeId4 = enumTypeId4;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId5 the enumTypeId5 to set
     */
    public void setEnumTypeId5(String enumTypeId5) {
        this.enumTypeId5 = enumTypeId5;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId6 the enumTypeId6 to set
     */
    public void setEnumTypeId6(String enumTypeId6) {
        this.enumTypeId6 = enumTypeId6;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId7 the enumTypeId7 to set
     */
    public void setEnumTypeId7(String enumTypeId7) {
        this.enumTypeId7 = enumTypeId7;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId8 the enumTypeId8 to set
     */
    public void setEnumTypeId8(String enumTypeId8) {
        this.enumTypeId8 = enumTypeId8;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId9 the enumTypeId9 to set
     */
    public void setEnumTypeId9(String enumTypeId9) {
        this.enumTypeId9 = enumTypeId9;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId10 the enumTypeId10 to set
     */
    public void setEnumTypeId10(String enumTypeId10) {
        this.enumTypeId10 = enumTypeId10;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum1Required the isTagEnum1Required to set
     */
    public void setIsTagEnum1Required(String isTagEnum1Required) {
        this.isTagEnum1Required = isTagEnum1Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum2Required the isTagEnum2Required to set
     */
    public void setIsTagEnum2Required(String isTagEnum2Required) {
        this.isTagEnum2Required = isTagEnum2Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum3Required the isTagEnum3Required to set
     */
    public void setIsTagEnum3Required(String isTagEnum3Required) {
        this.isTagEnum3Required = isTagEnum3Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum4Required the isTagEnum4Required to set
     */
    public void setIsTagEnum4Required(String isTagEnum4Required) {
        this.isTagEnum4Required = isTagEnum4Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum5Required the isTagEnum5Required to set
     */
    public void setIsTagEnum5Required(String isTagEnum5Required) {
        this.isTagEnum5Required = isTagEnum5Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum6Required the isTagEnum6Required to set
     */
    public void setIsTagEnum6Required(String isTagEnum6Required) {
        this.isTagEnum6Required = isTagEnum6Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum7Required the isTagEnum7Required to set
     */
    public void setIsTagEnum7Required(String isTagEnum7Required) {
        this.isTagEnum7Required = isTagEnum7Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum8Required the isTagEnum8Required to set
     */
    public void setIsTagEnum8Required(String isTagEnum8Required) {
        this.isTagEnum8Required = isTagEnum8Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum9Required the isTagEnum9Required to set
     */
    public void setIsTagEnum9Required(String isTagEnum9Required) {
        this.isTagEnum9Required = isTagEnum9Required;
    }
    /**
     * Auto generated value setter.
     * @param isTagEnum10Required the isTagEnum10Required to set
     */
    public void setIsTagEnum10Required(String isTagEnum10Required) {
        this.isTagEnum10Required = isTagEnum10Required;
    }
    /**
     * Auto generated value setter.
     * @param lastUpdatedStamp the lastUpdatedStamp to set
     */
    public void setLastUpdatedStamp(Timestamp lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }
    /**
     * Auto generated value setter.
     * @param lastUpdatedTxStamp the lastUpdatedTxStamp to set
     */
    public void setLastUpdatedTxStamp(Timestamp lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }
    /**
     * Auto generated value setter.
     * @param createdStamp the createdStamp to set
     */
    public void setCreatedStamp(Timestamp createdStamp) {
        this.createdStamp = createdStamp;
    }
    /**
     * Auto generated value setter.
     * @param createdTxStamp the createdTxStamp to set
     */
    public void setCreatedTxStamp(Timestamp createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getOrganizationPartyId() {
        return this.organizationPartyId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getAcctgTagUsageTypeId() {
        return this.acctgTagUsageTypeId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId1() {
        return this.enumTypeId1;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId2() {
        return this.enumTypeId2;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId3() {
        return this.enumTypeId3;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId4() {
        return this.enumTypeId4;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId5() {
        return this.enumTypeId5;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId6() {
        return this.enumTypeId6;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId7() {
        return this.enumTypeId7;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId8() {
        return this.enumTypeId8;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId9() {
        return this.enumTypeId9;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId10() {
        return this.enumTypeId10;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum1Required() {
        return this.isTagEnum1Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum2Required() {
        return this.isTagEnum2Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum3Required() {
        return this.isTagEnum3Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum4Required() {
        return this.isTagEnum4Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum5Required() {
        return this.isTagEnum5Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum6Required() {
        return this.isTagEnum6Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum7Required() {
        return this.isTagEnum7Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum8Required() {
        return this.isTagEnum8Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum9Required() {
        return this.isTagEnum9Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getIsTagEnum10Required() {
        return this.isTagEnum10Required;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getLastUpdatedStamp() {
        return this.lastUpdatedStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getLastUpdatedTxStamp() {
        return this.lastUpdatedTxStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getCreatedStamp() {
        return this.createdStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getCreatedTxStamp() {
        return this.createdTxStamp;
    }

    /**
     * Auto generated method that gets the related <code>Party</code> by the relation named <code>Party</code>.
     * @return the <code>Party</code>
     * @throws RepositoryException if an error occurs
     */
    public Party getParty() throws RepositoryException {
        if (this.party == null) {
            this.party = getRelatedOne(Party.class, "Party");
        }
        return this.party;
    }
    /**
     * Auto generated method that gets the related <code>AcctgTagUsageType</code> by the relation named <code>AcctgTagUsageType</code>.
     * @return the <code>AcctgTagUsageType</code>
     * @throws RepositoryException if an error occurs
     */
    public AcctgTagUsageType getAcctgTagUsageType() throws RepositoryException {
        if (this.acctgTagUsageType == null) {
            this.acctgTagUsageType = getRelatedOne(AcctgTagUsageType.class, "AcctgTagUsageType");
        }
        return this.acctgTagUsageType;
    }

    /**
     * Auto generated value setter.
     * @param party the party to set
    */
    public void setParty(Party party) {
        this.party = party;
    }
    /**
     * Auto generated value setter.
     * @param acctgTagUsageType the acctgTagUsageType to set
    */
    public void setAcctgTagUsageType(AcctgTagUsageType acctgTagUsageType) {
        this.acctgTagUsageType = acctgTagUsageType;
    }


    /** {@inheritDoc} */
    @Override
    public void fromMap(Map<String, Object> mapValue) {
        preInit();
        setOrganizationPartyId((String) mapValue.get("organizationPartyId"));
        setAcctgTagUsageTypeId((String) mapValue.get("acctgTagUsageTypeId"));
        setEnumTypeId1((String) mapValue.get("enumTypeId1"));
        setEnumTypeId2((String) mapValue.get("enumTypeId2"));
        setEnumTypeId3((String) mapValue.get("enumTypeId3"));
        setEnumTypeId4((String) mapValue.get("enumTypeId4"));
        setEnumTypeId5((String) mapValue.get("enumTypeId5"));
        setEnumTypeId6((String) mapValue.get("enumTypeId6"));
        setEnumTypeId7((String) mapValue.get("enumTypeId7"));
        setEnumTypeId8((String) mapValue.get("enumTypeId8"));
        setEnumTypeId9((String) mapValue.get("enumTypeId9"));
        setEnumTypeId10((String) mapValue.get("enumTypeId10"));
        setIsTagEnum1Required((String) mapValue.get("isTagEnum1Required"));
        setIsTagEnum2Required((String) mapValue.get("isTagEnum2Required"));
        setIsTagEnum3Required((String) mapValue.get("isTagEnum3Required"));
        setIsTagEnum4Required((String) mapValue.get("isTagEnum4Required"));
        setIsTagEnum5Required((String) mapValue.get("isTagEnum5Required"));
        setIsTagEnum6Required((String) mapValue.get("isTagEnum6Required"));
        setIsTagEnum7Required((String) mapValue.get("isTagEnum7Required"));
        setIsTagEnum8Required((String) mapValue.get("isTagEnum8Required"));
        setIsTagEnum9Required((String) mapValue.get("isTagEnum9Required"));
        setIsTagEnum10Required((String) mapValue.get("isTagEnum10Required"));
        setLastUpdatedStamp((Timestamp) mapValue.get("lastUpdatedStamp"));
        setLastUpdatedTxStamp((Timestamp) mapValue.get("lastUpdatedTxStamp"));
        setCreatedStamp((Timestamp) mapValue.get("createdStamp"));
        setCreatedTxStamp((Timestamp) mapValue.get("createdTxStamp"));
        postInit();
    }

    /** {@inheritDoc} */
    @Override
    public Map<String, Object> toMap() {
        Map<String, Object> mapValue = new FastMap<String, Object>();
        mapValue.put("organizationPartyId", getOrganizationPartyId());
        mapValue.put("acctgTagUsageTypeId", getAcctgTagUsageTypeId());
        mapValue.put("enumTypeId1", getEnumTypeId1());
        mapValue.put("enumTypeId2", getEnumTypeId2());
        mapValue.put("enumTypeId3", getEnumTypeId3());
        mapValue.put("enumTypeId4", getEnumTypeId4());
        mapValue.put("enumTypeId5", getEnumTypeId5());
        mapValue.put("enumTypeId6", getEnumTypeId6());
        mapValue.put("enumTypeId7", getEnumTypeId7());
        mapValue.put("enumTypeId8", getEnumTypeId8());
        mapValue.put("enumTypeId9", getEnumTypeId9());
        mapValue.put("enumTypeId10", getEnumTypeId10());
        mapValue.put("isTagEnum1Required", getIsTagEnum1Required());
        mapValue.put("isTagEnum2Required", getIsTagEnum2Required());
        mapValue.put("isTagEnum3Required", getIsTagEnum3Required());
        mapValue.put("isTagEnum4Required", getIsTagEnum4Required());
        mapValue.put("isTagEnum5Required", getIsTagEnum5Required());
        mapValue.put("isTagEnum6Required", getIsTagEnum6Required());
        mapValue.put("isTagEnum7Required", getIsTagEnum7Required());
        mapValue.put("isTagEnum8Required", getIsTagEnum8Required());
        mapValue.put("isTagEnum9Required", getIsTagEnum9Required());
        mapValue.put("isTagEnum10Required", getIsTagEnum10Required());
        mapValue.put("lastUpdatedStamp", getLastUpdatedStamp());
        mapValue.put("lastUpdatedTxStamp", getLastUpdatedTxStamp());
        mapValue.put("createdStamp", getCreatedStamp());
        mapValue.put("createdTxStamp", getCreatedTxStamp());
        return mapValue;
    }


}
