package org.opentaps.domain.base.entities;

/*
* Copyright (c) 2008 - 2009 Open Source Strategies, Inc.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the Honest Public License.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* Honest Public License for more details.
*
* You should have received a copy of the Honest Public License
* along with this program; if not, write to Funambol,
* 643 Bair Island Road, Suite 305 - Redwood City, CA 94063, USA
*/

// DO NOT EDIT THIS FILE!  THIS IS AUTO GENERATED AND WILL GET WRITTEN OVER PERIODICALLY WHEN THE DATA MODEL CHANGES
// EXTEND THIS CLASS INSTEAD.

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import javolution.util.FastMap;

import org.opentaps.foundation.entity.Entity;
import org.opentaps.foundation.entity.EntityFieldInterface;
import org.opentaps.foundation.repository.RepositoryException;
import org.opentaps.foundation.repository.RepositoryInterface;
import javax.persistence.*;
import java.lang.String;
import java.sql.Timestamp;

/**
 * Auto generated base entity Enumeration.
 */
@javax.persistence.Entity
@Table(name="ENUMERATION")
public class Enumeration extends Entity {
static {
java.util.Map<String, String> fields = new java.util.HashMap<String, String>();
        fields.put("enumId", "ENUM_ID");
        fields.put("enumTypeId", "ENUM_TYPE_ID");
        fields.put("enumCode", "ENUM_CODE");
        fields.put("sequenceId", "SEQUENCE_ID");
        fields.put("description", "DESCRIPTION");
        fields.put("lastUpdatedStamp", "LAST_UPDATED_STAMP");
        fields.put("lastUpdatedTxStamp", "LAST_UPDATED_TX_STAMP");
        fields.put("createdStamp", "CREATED_STAMP");
        fields.put("createdTxStamp", "CREATED_TX_STAMP");
        fields.put("parentEnumId", "PARENT_ENUM_ID");
fieldMapColumns.put("Enumeration", fields);
}
  public static enum Fields implements EntityFieldInterface<Enumeration> {
    enumId("enumId"),
    enumTypeId("enumTypeId"),
    enumCode("enumCode"),
    sequenceId("sequenceId"),
    description("description"),
    lastUpdatedStamp("lastUpdatedStamp"),
    lastUpdatedTxStamp("lastUpdatedTxStamp"),
    createdStamp("createdStamp"),
    createdTxStamp("createdTxStamp"),
    parentEnumId("parentEnumId");
    private final String fieldName;
    private Fields(String name) { fieldName = name; }
    /** {@inheritDoc} */
    public String getName() { return fieldName; }
    /** {@inheritDoc} */
    public String asc() { return fieldName + " ASC"; }
    /** {@inheritDoc} */
    public String desc() { return fieldName + " DESC"; }
  }

    @org.hibernate.annotations.GenericGenerator(name="Enumeration_GEN",  strategy="org.opentaps.foundation.entity.hibernate.OpentapsIdentifierGenerator")
    @GeneratedValue(generator="Enumeration_GEN")   
    @Id
    
    @Column(name="ENUM_ID")
    private String enumId;
    
    @Column(name="ENUM_TYPE_ID")
    private String enumTypeId;
    
    @Column(name="ENUM_CODE")
    private String enumCode;
    
    @Column(name="SEQUENCE_ID")
    private String sequenceId;
    
    @Column(name="DESCRIPTION")
    private String description;
    
    @Column(name="LAST_UPDATED_STAMP")
    private Timestamp lastUpdatedStamp;
    
    @Column(name="LAST_UPDATED_TX_STAMP")
    private Timestamp lastUpdatedTxStamp;
    
    @Column(name="CREATED_STAMP")
    private Timestamp createdStamp;
    
    @Column(name="CREATED_TX_STAMP")
    private Timestamp createdTxStamp;
    
    @Column(name="PARENT_ENUM_ID")
    private String parentEnumId;
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
    @JoinColumn(name="ENUM_TYPE_ID", insertable=false, updatable=false)
    @org.hibernate.annotations.Generated(
        org.hibernate.annotations.GenerationTime.ALWAYS
    )
    private EnumerationType enumerationType = null;
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
    @JoinColumn(name="PARENT_ENUM_ID", insertable=false, updatable=false)
    @org.hibernate.annotations.Generated(
        org.hibernate.annotations.GenerationTime.ALWAYS
    )
    private Enumeration enumeration = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="BALANCE_TYPE_ENUM_ID")
    private List<AccountBalanceHistory> balanceTypeAccountBalanceHistorys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="VALUE_ENUM_ID")
    private List<AgreementTerm> agreementTerms = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="PRIVILEGE_ENUM_ID")
    private List<Content> privilegeContents = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="CLASSIFICATION_ENUM_ID")
    private List<Content> classificationContents = null;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="enumeration", cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE})
    @JoinColumn(name="PRIVILEGE_ENUM_ID")
    private List<ContentPurposeOperation> contentPurposeOperations = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="SALES_CHANNEL_ENUM_ID")
    private List<CustRequest> salesChannelCustRequests = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="INVENTORY_RESERVE_ORDER_ENUM_ID")
    private List<Facility> facilitys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="LOCATION_TYPE_ENUM_ID")
    private List<FacilityLocation> typeFacilityLocations = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="REPLENISH_ENUM_ID")
    private List<FinAccountType> replenishFinAccountTypes = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="CLASS_ENUM_ID")
    private List<FixedAsset> classFixedAssets = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPE_ENUM_ID")
    private List<GiftCardFulfillment> giftCardFulfillments = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="REASON_ENUM_ID")
    private List<InventoryItemDetail> reasonInventoryItemDetails = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="RELATIONSHIP_ENUM_ID")
    private List<KeywordThesaurus> relationshipKeywordThesauruses = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPE_ENUM_ID")
    private List<OldValueLinkFulfillment> oldValueLinkFulfillments = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="SALES_CHANNEL_ENUM_ID")
    private List<OrderHeader> salesChannelOrderHeaders = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="EMAIL_TYPE")
    private List<OrderNotification> orderNotifications = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="TAX_FORM_ID")
    private List<PartyAcctgPreference> taxFormPartyAcctgPreferences = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="COGS_METHOD_ID")
    private List<PartyAcctgPreference> cogsPartyAcctgPreferences = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="INVOICE_SEQUENCE_ENUM_ID")
    private List<PartyAcctgPreference> invoiceSequencePartyAcctgPreferences = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="QUOTE_SEQUENCE_ENUM_ID")
    private List<PartyAcctgPreference> quoteSequencePartyAcctgPreferences = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="ORDER_SEQUENCE_ENUM_ID")
    private List<PartyAcctgPreference> orderSequencePartyAcctgPreferences = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="COSTING_METHOD_ID")
    private List<PartyAcctgPreference> costingMethodPartyAcctgPreferences = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTENT_PURPOSE_ENUM_ID")
    private List<PartyContent> partyContents = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="INDUSTRY_ENUM_ID")
    private List<PartySupplementalData> industryPartySupplementalDatas = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="OWNERSHIP_ENUM_ID")
    private List<PartySupplementalData> ownershipPartySupplementalDatas = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="PAYMENT_SERVICE_TYPE_ENUM_ID")
    private List<PaymentGatewayResponse> serviceTypePaymentGatewayResponses = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="TRANS_CODE_ENUM_ID")
    private List<PaymentGatewayResponse> tranCodePaymentGatewayResponses = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYMENT_STATUS_ENUM_ID")
    private List<Person> employmentStatuspeople = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="RESIDENCE_STATUS_ENUM_ID")
    private List<Person> residenceStatuspeople = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="RATING_TYPE_ENUM")
    private List<Product> ratingProducts = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="REQUIREMENT_METHOD_ENUM_ID")
    private List<Product> requirementMethodProducts = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="LINK_TYPE_ENUM_ID")
    private List<ProductCategoryLink> linkTypeProductCategoryLinks = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="REPLENISH_METHOD_ENUM_ID")
    private List<ProductFacility> resplenishMethodProductFacilitys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_GEO_ENUM_ID")
    private List<ProductGeo> productGeos = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="INPUT_PARAM_ENUM_ID")
    private List<ProductPriceCond> inputParamProductPriceConds = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="OPERATOR_ENUM_ID")
    private List<ProductPriceCond> operatorProductPriceConds = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_PROMO_ACTION_ENUM_ID")
    private List<ProductPromoAction> actionProductPromoActions = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_PROMO_APPL_ENUM_ID")
    private List<ProductPromoCategory> applProductPromoCategorys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="INPUT_PARAM_ENUM_ID")
    private List<ProductPromoCond> inputParamProductPromoConds = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="OPERATOR_ENUM_ID")
    private List<ProductPromoCond> operatorProductPromoConds = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_PROMO_APPL_ENUM_ID")
    private List<ProductPromoProduct> applProductPromoProducts = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="RESERVE_ORDER_ENUM_ID")
    private List<ProductStore> reserveOrderProductStores = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="REQUIREMENT_METHOD_ENUM_ID")
    private List<ProductStore> requirementMethodProductStores = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="DEFAULT_SALES_CHANNEL_ENUM_ID")
    private List<ProductStore> defaultSalesChannelProductStores = null;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="enumeration", cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE})
    @JoinColumn(name="EMAIL_TYPE")
    private List<ProductStoreEmailSetting> productStoreEmailSettings = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="TARGET_TYPE_ENUM_ID")
    private List<ProductStoreKeywordOvrd> productStoreKeywordOvrds = null;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="enumeration", cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE})
    @JoinColumn(name="PAYMENT_SERVICE_TYPE_ENUM_ID")
    private List<ProductStorePaymentSetting> productStorePaymentSettings = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="SALES_CHANNEL_ENUM_ID")
    private List<Quote> salesChannelQuotes = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPE_ENUM_ID")
    private List<SalesOpportunity> typeSalesOpportunitys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="ENUM_ID")
    private List<TestEntity> testEntitys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="SOURCE_ENUM_ID")
    private List<TrackingCodeVisit> trackingCodeVisits = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="VIEW_PREF_ENUM_ID")
    private List<ViewPreference> viewPreferences = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="SCOPE_ENUM_ID")
    private List<WorkEffort> scopeWorkEfforts = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="EXPECTATION_ENUM_ID")
    private List<WorkEffortPartyAssignment> expectationWorkEffortPartyAssignments = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="START_MODE_ENUM_ID")
    private List<WorkflowActivity> startModeWorkflowActivitys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="FINISH_MODE_ENUM_ID")
    private List<WorkflowActivity> finishModeWorkflowActivitys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="JOIN_TYPE_ENUM_ID")
    private List<WorkflowActivity> joinWorkflowActivitys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="SPLIT_TYPE_ENUM_ID")
    private List<WorkflowActivity> splitWorkflowActivitys = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="DATA_TYPE_ENUM_ID")
    private List<WorkflowComplexTypeInfo> dataTypeWorkflowComplexTypeInfoes = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="DATA_TYPE_ENUM_ID")
    private List<WorkflowDataField> dataTypeWorkflowDataFields = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="MODE_ENUM_ID")
    private List<WorkflowFormalParam> modeWorkflowFormalParams = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="DATA_TYPE_ENUM_ID")
    private List<WorkflowFormalParam> dataTypeWorkflowFormalParams = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="GRAPH_CONFORMANCE_ENUM_ID")
    private List<WorkflowPackage> graphConformanceWorkflowPackages = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="CONDITION_TYPE_ENUM_ID")
    private List<WorkflowTransition> conditionTypeWorkflowTransitions = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="LOOP_TYPE_ENUM_ID")
    private List<WorkflowTransition> loopTypeWorkflowTransitions = null;
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="DATA_TYPE_ENUM_ID")
    private List<WorkflowTypeDeclaration> dataTypeWorkflowTypeDeclarations = null;

  /**
   * Default constructor.
   */
  public Enumeration() {
      super();
      this.baseEntityName = "Enumeration";
      this.isView = false;
      this.resourceName = "CommonEntityLabels";
      this.primaryKeyNames = new ArrayList<String>();
      this.primaryKeyNames.add("enumId");
  }

  /**
   * Constructor with a repository.
   * @param repository a <code>RepositoryInterface</code> value
   */
  public Enumeration(RepositoryInterface repository) {
      this();
      initRepository(repository);
  }

    /**
     * Auto generated value setter.
     * @param enumId the enumId to set
     */
    public void setEnumId(String enumId) {
        this.enumId = enumId;
    }
    /**
     * Auto generated value setter.
     * @param enumTypeId the enumTypeId to set
     */
    public void setEnumTypeId(String enumTypeId) {
        this.enumTypeId = enumTypeId;
    }
    /**
     * Auto generated value setter.
     * @param enumCode the enumCode to set
     */
    public void setEnumCode(String enumCode) {
        this.enumCode = enumCode;
    }
    /**
     * Auto generated value setter.
     * @param sequenceId the sequenceId to set
     */
    public void setSequenceId(String sequenceId) {
        this.sequenceId = sequenceId;
    }
    /**
     * Auto generated value setter.
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Auto generated value setter.
     * @param lastUpdatedStamp the lastUpdatedStamp to set
     */
    public void setLastUpdatedStamp(Timestamp lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }
    /**
     * Auto generated value setter.
     * @param lastUpdatedTxStamp the lastUpdatedTxStamp to set
     */
    public void setLastUpdatedTxStamp(Timestamp lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }
    /**
     * Auto generated value setter.
     * @param createdStamp the createdStamp to set
     */
    public void setCreatedStamp(Timestamp createdStamp) {
        this.createdStamp = createdStamp;
    }
    /**
     * Auto generated value setter.
     * @param createdTxStamp the createdTxStamp to set
     */
    public void setCreatedTxStamp(Timestamp createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }
    /**
     * Auto generated value setter.
     * @param parentEnumId the parentEnumId to set
     */
    public void setParentEnumId(String parentEnumId) {
        this.parentEnumId = parentEnumId;
    }

    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumId() {
        return this.enumId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumTypeId() {
        return this.enumTypeId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getEnumCode() {
        return this.enumCode;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getSequenceId() {
        return this.sequenceId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getDescription() {
        return this.description;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getLastUpdatedStamp() {
        return this.lastUpdatedStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getLastUpdatedTxStamp() {
        return this.lastUpdatedTxStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getCreatedStamp() {
        return this.createdStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getCreatedTxStamp() {
        return this.createdTxStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getParentEnumId() {
        return this.parentEnumId;
    }

    /**
     * Auto generated method that gets the related <code>EnumerationType</code> by the relation named <code>EnumerationType</code>.
     * @return the <code>EnumerationType</code>
     * @throws RepositoryException if an error occurs
     */
    public EnumerationType getEnumerationType() throws RepositoryException {
        if (this.enumerationType == null) {
            this.enumerationType = getRelatedOne(EnumerationType.class, "EnumerationType");
        }
        return this.enumerationType;
    }
    /**
     * Auto generated method that gets the related <code>Enumeration</code> by the relation named <code>Enumeration</code>.
     * @return the <code>Enumeration</code>
     * @throws RepositoryException if an error occurs
     */
    public Enumeration getEnumeration() throws RepositoryException {
        if (this.enumeration == null) {
            this.enumeration = getRelatedOne(Enumeration.class, "Enumeration");
        }
        return this.enumeration;
    }
    /**
     * Auto generated method that gets the related <code>AccountBalanceHistory</code> by the relation named <code>BalanceTypeAccountBalanceHistory</code>.
     * @return the list of <code>AccountBalanceHistory</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends AccountBalanceHistory> getBalanceTypeAccountBalanceHistorys() throws RepositoryException {
        if (this.balanceTypeAccountBalanceHistorys == null) {
            this.balanceTypeAccountBalanceHistorys = getRelated(AccountBalanceHistory.class, "BalanceTypeAccountBalanceHistory");
        }
        return this.balanceTypeAccountBalanceHistorys;
    }
    /**
     * Auto generated method that gets the related <code>AgreementTerm</code> by the relation named <code>AgreementTerm</code>.
     * @return the list of <code>AgreementTerm</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends AgreementTerm> getAgreementTerms() throws RepositoryException {
        if (this.agreementTerms == null) {
            this.agreementTerms = getRelated(AgreementTerm.class, "AgreementTerm");
        }
        return this.agreementTerms;
    }
    /**
     * Auto generated method that gets the related <code>Content</code> by the relation named <code>PrivilegeContent</code>.
     * @return the list of <code>Content</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends Content> getPrivilegeContents() throws RepositoryException {
        if (this.privilegeContents == null) {
            this.privilegeContents = getRelated(Content.class, "PrivilegeContent");
        }
        return this.privilegeContents;
    }
    /**
     * Auto generated method that gets the related <code>Content</code> by the relation named <code>ClassificationContent</code>.
     * @return the list of <code>Content</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends Content> getClassificationContents() throws RepositoryException {
        if (this.classificationContents == null) {
            this.classificationContents = getRelated(Content.class, "ClassificationContent");
        }
        return this.classificationContents;
    }
    /**
     * Auto generated method that gets the related <code>ContentPurposeOperation</code> by the relation named <code>ContentPurposeOperation</code>.
     * @return the list of <code>ContentPurposeOperation</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ContentPurposeOperation> getContentPurposeOperations() throws RepositoryException {
        if (this.contentPurposeOperations == null) {
            this.contentPurposeOperations = getRelated(ContentPurposeOperation.class, "ContentPurposeOperation");
        }
        return this.contentPurposeOperations;
    }
    /**
     * Auto generated method that gets the related <code>CustRequest</code> by the relation named <code>SalesChannelCustRequest</code>.
     * @return the list of <code>CustRequest</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends CustRequest> getSalesChannelCustRequests() throws RepositoryException {
        if (this.salesChannelCustRequests == null) {
            this.salesChannelCustRequests = getRelated(CustRequest.class, "SalesChannelCustRequest");
        }
        return this.salesChannelCustRequests;
    }
    /**
     * Auto generated method that gets the related <code>Facility</code> by the relation named <code>Facility</code>.
     * @return the list of <code>Facility</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends Facility> getFacilitys() throws RepositoryException {
        if (this.facilitys == null) {
            this.facilitys = getRelated(Facility.class, "Facility");
        }
        return this.facilitys;
    }
    /**
     * Auto generated method that gets the related <code>FacilityLocation</code> by the relation named <code>TypeFacilityLocation</code>.
     * @return the list of <code>FacilityLocation</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends FacilityLocation> getTypeFacilityLocations() throws RepositoryException {
        if (this.typeFacilityLocations == null) {
            this.typeFacilityLocations = getRelated(FacilityLocation.class, "TypeFacilityLocation");
        }
        return this.typeFacilityLocations;
    }
    /**
     * Auto generated method that gets the related <code>FinAccountType</code> by the relation named <code>ReplenishFinAccountType</code>.
     * @return the list of <code>FinAccountType</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends FinAccountType> getReplenishFinAccountTypes() throws RepositoryException {
        if (this.replenishFinAccountTypes == null) {
            this.replenishFinAccountTypes = getRelated(FinAccountType.class, "ReplenishFinAccountType");
        }
        return this.replenishFinAccountTypes;
    }
    /**
     * Auto generated method that gets the related <code>FixedAsset</code> by the relation named <code>ClassFixedAsset</code>.
     * @return the list of <code>FixedAsset</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends FixedAsset> getClassFixedAssets() throws RepositoryException {
        if (this.classFixedAssets == null) {
            this.classFixedAssets = getRelated(FixedAsset.class, "ClassFixedAsset");
        }
        return this.classFixedAssets;
    }
    /**
     * Auto generated method that gets the related <code>GiftCardFulfillment</code> by the relation named <code>GiftCardFulfillment</code>.
     * @return the list of <code>GiftCardFulfillment</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends GiftCardFulfillment> getGiftCardFulfillments() throws RepositoryException {
        if (this.giftCardFulfillments == null) {
            this.giftCardFulfillments = getRelated(GiftCardFulfillment.class, "GiftCardFulfillment");
        }
        return this.giftCardFulfillments;
    }
    /**
     * Auto generated method that gets the related <code>InventoryItemDetail</code> by the relation named <code>ReasonInventoryItemDetail</code>.
     * @return the list of <code>InventoryItemDetail</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends InventoryItemDetail> getReasonInventoryItemDetails() throws RepositoryException {
        if (this.reasonInventoryItemDetails == null) {
            this.reasonInventoryItemDetails = getRelated(InventoryItemDetail.class, "ReasonInventoryItemDetail");
        }
        return this.reasonInventoryItemDetails;
    }
    /**
     * Auto generated method that gets the related <code>KeywordThesaurus</code> by the relation named <code>RelationshipKeywordThesaurus</code>.
     * @return the list of <code>KeywordThesaurus</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends KeywordThesaurus> getRelationshipKeywordThesauruses() throws RepositoryException {
        if (this.relationshipKeywordThesauruses == null) {
            this.relationshipKeywordThesauruses = getRelated(KeywordThesaurus.class, "RelationshipKeywordThesaurus");
        }
        return this.relationshipKeywordThesauruses;
    }
    /**
     * Auto generated method that gets the related <code>OldValueLinkFulfillment</code> by the relation named <code>OldValueLinkFulfillment</code>.
     * @return the list of <code>OldValueLinkFulfillment</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends OldValueLinkFulfillment> getOldValueLinkFulfillments() throws RepositoryException {
        if (this.oldValueLinkFulfillments == null) {
            this.oldValueLinkFulfillments = getRelated(OldValueLinkFulfillment.class, "OldValueLinkFulfillment");
        }
        return this.oldValueLinkFulfillments;
    }
    /**
     * Auto generated method that gets the related <code>OrderHeader</code> by the relation named <code>SalesChannelOrderHeader</code>.
     * @return the list of <code>OrderHeader</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends OrderHeader> getSalesChannelOrderHeaders() throws RepositoryException {
        if (this.salesChannelOrderHeaders == null) {
            this.salesChannelOrderHeaders = getRelated(OrderHeader.class, "SalesChannelOrderHeader");
        }
        return this.salesChannelOrderHeaders;
    }
    /**
     * Auto generated method that gets the related <code>OrderNotification</code> by the relation named <code>OrderNotification</code>.
     * @return the list of <code>OrderNotification</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends OrderNotification> getOrderNotifications() throws RepositoryException {
        if (this.orderNotifications == null) {
            this.orderNotifications = getRelated(OrderNotification.class, "OrderNotification");
        }
        return this.orderNotifications;
    }
    /**
     * Auto generated method that gets the related <code>PartyAcctgPreference</code> by the relation named <code>TaxFormPartyAcctgPreference</code>.
     * @return the list of <code>PartyAcctgPreference</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartyAcctgPreference> getTaxFormPartyAcctgPreferences() throws RepositoryException {
        if (this.taxFormPartyAcctgPreferences == null) {
            this.taxFormPartyAcctgPreferences = getRelated(PartyAcctgPreference.class, "TaxFormPartyAcctgPreference");
        }
        return this.taxFormPartyAcctgPreferences;
    }
    /**
     * Auto generated method that gets the related <code>PartyAcctgPreference</code> by the relation named <code>CogsPartyAcctgPreference</code>.
     * @return the list of <code>PartyAcctgPreference</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartyAcctgPreference> getCogsPartyAcctgPreferences() throws RepositoryException {
        if (this.cogsPartyAcctgPreferences == null) {
            this.cogsPartyAcctgPreferences = getRelated(PartyAcctgPreference.class, "CogsPartyAcctgPreference");
        }
        return this.cogsPartyAcctgPreferences;
    }
    /**
     * Auto generated method that gets the related <code>PartyAcctgPreference</code> by the relation named <code>InvoiceSequencePartyAcctgPreference</code>.
     * @return the list of <code>PartyAcctgPreference</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartyAcctgPreference> getInvoiceSequencePartyAcctgPreferences() throws RepositoryException {
        if (this.invoiceSequencePartyAcctgPreferences == null) {
            this.invoiceSequencePartyAcctgPreferences = getRelated(PartyAcctgPreference.class, "InvoiceSequencePartyAcctgPreference");
        }
        return this.invoiceSequencePartyAcctgPreferences;
    }
    /**
     * Auto generated method that gets the related <code>PartyAcctgPreference</code> by the relation named <code>QuoteSequencePartyAcctgPreference</code>.
     * @return the list of <code>PartyAcctgPreference</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartyAcctgPreference> getQuoteSequencePartyAcctgPreferences() throws RepositoryException {
        if (this.quoteSequencePartyAcctgPreferences == null) {
            this.quoteSequencePartyAcctgPreferences = getRelated(PartyAcctgPreference.class, "QuoteSequencePartyAcctgPreference");
        }
        return this.quoteSequencePartyAcctgPreferences;
    }
    /**
     * Auto generated method that gets the related <code>PartyAcctgPreference</code> by the relation named <code>OrderSequencePartyAcctgPreference</code>.
     * @return the list of <code>PartyAcctgPreference</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartyAcctgPreference> getOrderSequencePartyAcctgPreferences() throws RepositoryException {
        if (this.orderSequencePartyAcctgPreferences == null) {
            this.orderSequencePartyAcctgPreferences = getRelated(PartyAcctgPreference.class, "OrderSequencePartyAcctgPreference");
        }
        return this.orderSequencePartyAcctgPreferences;
    }
    /**
     * Auto generated method that gets the related <code>PartyAcctgPreference</code> by the relation named <code>CostingMethodPartyAcctgPreference</code>.
     * @return the list of <code>PartyAcctgPreference</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartyAcctgPreference> getCostingMethodPartyAcctgPreferences() throws RepositoryException {
        if (this.costingMethodPartyAcctgPreferences == null) {
            this.costingMethodPartyAcctgPreferences = getRelated(PartyAcctgPreference.class, "CostingMethodPartyAcctgPreference");
        }
        return this.costingMethodPartyAcctgPreferences;
    }
    /**
     * Auto generated method that gets the related <code>PartyContent</code> by the relation named <code>PartyContent</code>.
     * @return the list of <code>PartyContent</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartyContent> getPartyContents() throws RepositoryException {
        if (this.partyContents == null) {
            this.partyContents = getRelated(PartyContent.class, "PartyContent");
        }
        return this.partyContents;
    }
    /**
     * Auto generated method that gets the related <code>PartySupplementalData</code> by the relation named <code>IndustryPartySupplementalData</code>.
     * @return the list of <code>PartySupplementalData</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartySupplementalData> getIndustryPartySupplementalDatas() throws RepositoryException {
        if (this.industryPartySupplementalDatas == null) {
            this.industryPartySupplementalDatas = getRelated(PartySupplementalData.class, "IndustryPartySupplementalData");
        }
        return this.industryPartySupplementalDatas;
    }
    /**
     * Auto generated method that gets the related <code>PartySupplementalData</code> by the relation named <code>OwnershipPartySupplementalData</code>.
     * @return the list of <code>PartySupplementalData</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PartySupplementalData> getOwnershipPartySupplementalDatas() throws RepositoryException {
        if (this.ownershipPartySupplementalDatas == null) {
            this.ownershipPartySupplementalDatas = getRelated(PartySupplementalData.class, "OwnershipPartySupplementalData");
        }
        return this.ownershipPartySupplementalDatas;
    }
    /**
     * Auto generated method that gets the related <code>PaymentGatewayResponse</code> by the relation named <code>ServiceTypePaymentGatewayResponse</code>.
     * @return the list of <code>PaymentGatewayResponse</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PaymentGatewayResponse> getServiceTypePaymentGatewayResponses() throws RepositoryException {
        if (this.serviceTypePaymentGatewayResponses == null) {
            this.serviceTypePaymentGatewayResponses = getRelated(PaymentGatewayResponse.class, "ServiceTypePaymentGatewayResponse");
        }
        return this.serviceTypePaymentGatewayResponses;
    }
    /**
     * Auto generated method that gets the related <code>PaymentGatewayResponse</code> by the relation named <code>TranCodePaymentGatewayResponse</code>.
     * @return the list of <code>PaymentGatewayResponse</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends PaymentGatewayResponse> getTranCodePaymentGatewayResponses() throws RepositoryException {
        if (this.tranCodePaymentGatewayResponses == null) {
            this.tranCodePaymentGatewayResponses = getRelated(PaymentGatewayResponse.class, "TranCodePaymentGatewayResponse");
        }
        return this.tranCodePaymentGatewayResponses;
    }
    /**
     * Auto generated method that gets the related <code>Person</code> by the relation named <code>EmploymentStatusPerson</code>.
     * @return the list of <code>Person</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends Person> getEmploymentStatuspeople() throws RepositoryException {
        if (this.employmentStatuspeople == null) {
            this.employmentStatuspeople = getRelated(Person.class, "EmploymentStatusPerson");
        }
        return this.employmentStatuspeople;
    }
    /**
     * Auto generated method that gets the related <code>Person</code> by the relation named <code>ResidenceStatusPerson</code>.
     * @return the list of <code>Person</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends Person> getResidenceStatuspeople() throws RepositoryException {
        if (this.residenceStatuspeople == null) {
            this.residenceStatuspeople = getRelated(Person.class, "ResidenceStatusPerson");
        }
        return this.residenceStatuspeople;
    }
    /**
     * Auto generated method that gets the related <code>Product</code> by the relation named <code>RatingProduct</code>.
     * @return the list of <code>Product</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends Product> getRatingProducts() throws RepositoryException {
        if (this.ratingProducts == null) {
            this.ratingProducts = getRelated(Product.class, "RatingProduct");
        }
        return this.ratingProducts;
    }
    /**
     * Auto generated method that gets the related <code>Product</code> by the relation named <code>RequirementMethodProduct</code>.
     * @return the list of <code>Product</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends Product> getRequirementMethodProducts() throws RepositoryException {
        if (this.requirementMethodProducts == null) {
            this.requirementMethodProducts = getRelated(Product.class, "RequirementMethodProduct");
        }
        return this.requirementMethodProducts;
    }
    /**
     * Auto generated method that gets the related <code>ProductCategoryLink</code> by the relation named <code>LinkTypeProductCategoryLink</code>.
     * @return the list of <code>ProductCategoryLink</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductCategoryLink> getLinkTypeProductCategoryLinks() throws RepositoryException {
        if (this.linkTypeProductCategoryLinks == null) {
            this.linkTypeProductCategoryLinks = getRelated(ProductCategoryLink.class, "LinkTypeProductCategoryLink");
        }
        return this.linkTypeProductCategoryLinks;
    }
    /**
     * Auto generated method that gets the related <code>ProductFacility</code> by the relation named <code>ResplenishMethodProductFacility</code>.
     * @return the list of <code>ProductFacility</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductFacility> getResplenishMethodProductFacilitys() throws RepositoryException {
        if (this.resplenishMethodProductFacilitys == null) {
            this.resplenishMethodProductFacilitys = getRelated(ProductFacility.class, "ResplenishMethodProductFacility");
        }
        return this.resplenishMethodProductFacilitys;
    }
    /**
     * Auto generated method that gets the related <code>ProductGeo</code> by the relation named <code>ProductGeo</code>.
     * @return the list of <code>ProductGeo</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductGeo> getProductGeos() throws RepositoryException {
        if (this.productGeos == null) {
            this.productGeos = getRelated(ProductGeo.class, "ProductGeo");
        }
        return this.productGeos;
    }
    /**
     * Auto generated method that gets the related <code>ProductPriceCond</code> by the relation named <code>InputParamProductPriceCond</code>.
     * @return the list of <code>ProductPriceCond</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductPriceCond> getInputParamProductPriceConds() throws RepositoryException {
        if (this.inputParamProductPriceConds == null) {
            this.inputParamProductPriceConds = getRelated(ProductPriceCond.class, "InputParamProductPriceCond");
        }
        return this.inputParamProductPriceConds;
    }
    /**
     * Auto generated method that gets the related <code>ProductPriceCond</code> by the relation named <code>OperatorProductPriceCond</code>.
     * @return the list of <code>ProductPriceCond</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductPriceCond> getOperatorProductPriceConds() throws RepositoryException {
        if (this.operatorProductPriceConds == null) {
            this.operatorProductPriceConds = getRelated(ProductPriceCond.class, "OperatorProductPriceCond");
        }
        return this.operatorProductPriceConds;
    }
    /**
     * Auto generated method that gets the related <code>ProductPromoAction</code> by the relation named <code>ActionProductPromoAction</code>.
     * @return the list of <code>ProductPromoAction</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductPromoAction> getActionProductPromoActions() throws RepositoryException {
        if (this.actionProductPromoActions == null) {
            this.actionProductPromoActions = getRelated(ProductPromoAction.class, "ActionProductPromoAction");
        }
        return this.actionProductPromoActions;
    }
    /**
     * Auto generated method that gets the related <code>ProductPromoCategory</code> by the relation named <code>ApplProductPromoCategory</code>.
     * @return the list of <code>ProductPromoCategory</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductPromoCategory> getApplProductPromoCategorys() throws RepositoryException {
        if (this.applProductPromoCategorys == null) {
            this.applProductPromoCategorys = getRelated(ProductPromoCategory.class, "ApplProductPromoCategory");
        }
        return this.applProductPromoCategorys;
    }
    /**
     * Auto generated method that gets the related <code>ProductPromoCond</code> by the relation named <code>InputParamProductPromoCond</code>.
     * @return the list of <code>ProductPromoCond</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductPromoCond> getInputParamProductPromoConds() throws RepositoryException {
        if (this.inputParamProductPromoConds == null) {
            this.inputParamProductPromoConds = getRelated(ProductPromoCond.class, "InputParamProductPromoCond");
        }
        return this.inputParamProductPromoConds;
    }
    /**
     * Auto generated method that gets the related <code>ProductPromoCond</code> by the relation named <code>OperatorProductPromoCond</code>.
     * @return the list of <code>ProductPromoCond</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductPromoCond> getOperatorProductPromoConds() throws RepositoryException {
        if (this.operatorProductPromoConds == null) {
            this.operatorProductPromoConds = getRelated(ProductPromoCond.class, "OperatorProductPromoCond");
        }
        return this.operatorProductPromoConds;
    }
    /**
     * Auto generated method that gets the related <code>ProductPromoProduct</code> by the relation named <code>ApplProductPromoProduct</code>.
     * @return the list of <code>ProductPromoProduct</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductPromoProduct> getApplProductPromoProducts() throws RepositoryException {
        if (this.applProductPromoProducts == null) {
            this.applProductPromoProducts = getRelated(ProductPromoProduct.class, "ApplProductPromoProduct");
        }
        return this.applProductPromoProducts;
    }
    /**
     * Auto generated method that gets the related <code>ProductStore</code> by the relation named <code>ReserveOrderProductStore</code>.
     * @return the list of <code>ProductStore</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductStore> getReserveOrderProductStores() throws RepositoryException {
        if (this.reserveOrderProductStores == null) {
            this.reserveOrderProductStores = getRelated(ProductStore.class, "ReserveOrderProductStore");
        }
        return this.reserveOrderProductStores;
    }
    /**
     * Auto generated method that gets the related <code>ProductStore</code> by the relation named <code>RequirementMethodProductStore</code>.
     * @return the list of <code>ProductStore</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductStore> getRequirementMethodProductStores() throws RepositoryException {
        if (this.requirementMethodProductStores == null) {
            this.requirementMethodProductStores = getRelated(ProductStore.class, "RequirementMethodProductStore");
        }
        return this.requirementMethodProductStores;
    }
    /**
     * Auto generated method that gets the related <code>ProductStore</code> by the relation named <code>DefaultSalesChannelProductStore</code>.
     * @return the list of <code>ProductStore</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductStore> getDefaultSalesChannelProductStores() throws RepositoryException {
        if (this.defaultSalesChannelProductStores == null) {
            this.defaultSalesChannelProductStores = getRelated(ProductStore.class, "DefaultSalesChannelProductStore");
        }
        return this.defaultSalesChannelProductStores;
    }
    /**
     * Auto generated method that gets the related <code>ProductStoreEmailSetting</code> by the relation named <code>ProductStoreEmailSetting</code>.
     * @return the list of <code>ProductStoreEmailSetting</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductStoreEmailSetting> getProductStoreEmailSettings() throws RepositoryException {
        if (this.productStoreEmailSettings == null) {
            this.productStoreEmailSettings = getRelated(ProductStoreEmailSetting.class, "ProductStoreEmailSetting");
        }
        return this.productStoreEmailSettings;
    }
    /**
     * Auto generated method that gets the related <code>ProductStoreKeywordOvrd</code> by the relation named <code>ProductStoreKeywordOvrd</code>.
     * @return the list of <code>ProductStoreKeywordOvrd</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductStoreKeywordOvrd> getProductStoreKeywordOvrds() throws RepositoryException {
        if (this.productStoreKeywordOvrds == null) {
            this.productStoreKeywordOvrds = getRelated(ProductStoreKeywordOvrd.class, "ProductStoreKeywordOvrd");
        }
        return this.productStoreKeywordOvrds;
    }
    /**
     * Auto generated method that gets the related <code>ProductStorePaymentSetting</code> by the relation named <code>ProductStorePaymentSetting</code>.
     * @return the list of <code>ProductStorePaymentSetting</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ProductStorePaymentSetting> getProductStorePaymentSettings() throws RepositoryException {
        if (this.productStorePaymentSettings == null) {
            this.productStorePaymentSettings = getRelated(ProductStorePaymentSetting.class, "ProductStorePaymentSetting");
        }
        return this.productStorePaymentSettings;
    }
    /**
     * Auto generated method that gets the related <code>Quote</code> by the relation named <code>SalesChannelQuote</code>.
     * @return the list of <code>Quote</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends Quote> getSalesChannelQuotes() throws RepositoryException {
        if (this.salesChannelQuotes == null) {
            this.salesChannelQuotes = getRelated(Quote.class, "SalesChannelQuote");
        }
        return this.salesChannelQuotes;
    }
    /**
     * Auto generated method that gets the related <code>SalesOpportunity</code> by the relation named <code>TypeSalesOpportunity</code>.
     * @return the list of <code>SalesOpportunity</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends SalesOpportunity> getTypeSalesOpportunitys() throws RepositoryException {
        if (this.typeSalesOpportunitys == null) {
            this.typeSalesOpportunitys = getRelated(SalesOpportunity.class, "TypeSalesOpportunity");
        }
        return this.typeSalesOpportunitys;
    }
    /**
     * Auto generated method that gets the related <code>TestEntity</code> by the relation named <code>TestEntity</code>.
     * @return the list of <code>TestEntity</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends TestEntity> getTestEntitys() throws RepositoryException {
        if (this.testEntitys == null) {
            this.testEntitys = getRelated(TestEntity.class, "TestEntity");
        }
        return this.testEntitys;
    }
    /**
     * Auto generated method that gets the related <code>TrackingCodeVisit</code> by the relation named <code>TrackingCodeVisit</code>.
     * @return the list of <code>TrackingCodeVisit</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends TrackingCodeVisit> getTrackingCodeVisits() throws RepositoryException {
        if (this.trackingCodeVisits == null) {
            this.trackingCodeVisits = getRelated(TrackingCodeVisit.class, "TrackingCodeVisit");
        }
        return this.trackingCodeVisits;
    }
    /**
     * Auto generated method that gets the related <code>ViewPreference</code> by the relation named <code>ViewPreference</code>.
     * @return the list of <code>ViewPreference</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends ViewPreference> getViewPreferences() throws RepositoryException {
        if (this.viewPreferences == null) {
            this.viewPreferences = getRelated(ViewPreference.class, "ViewPreference");
        }
        return this.viewPreferences;
    }
    /**
     * Auto generated method that gets the related <code>WorkEffort</code> by the relation named <code>ScopeWorkEffort</code>.
     * @return the list of <code>WorkEffort</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkEffort> getScopeWorkEfforts() throws RepositoryException {
        if (this.scopeWorkEfforts == null) {
            this.scopeWorkEfforts = getRelated(WorkEffort.class, "ScopeWorkEffort");
        }
        return this.scopeWorkEfforts;
    }
    /**
     * Auto generated method that gets the related <code>WorkEffortPartyAssignment</code> by the relation named <code>ExpectationWorkEffortPartyAssignment</code>.
     * @return the list of <code>WorkEffortPartyAssignment</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkEffortPartyAssignment> getExpectationWorkEffortPartyAssignments() throws RepositoryException {
        if (this.expectationWorkEffortPartyAssignments == null) {
            this.expectationWorkEffortPartyAssignments = getRelated(WorkEffortPartyAssignment.class, "ExpectationWorkEffortPartyAssignment");
        }
        return this.expectationWorkEffortPartyAssignments;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowActivity</code> by the relation named <code>StartModeWorkflowActivity</code>.
     * @return the list of <code>WorkflowActivity</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowActivity> getStartModeWorkflowActivitys() throws RepositoryException {
        if (this.startModeWorkflowActivitys == null) {
            this.startModeWorkflowActivitys = getRelated(WorkflowActivity.class, "StartModeWorkflowActivity");
        }
        return this.startModeWorkflowActivitys;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowActivity</code> by the relation named <code>FinishModeWorkflowActivity</code>.
     * @return the list of <code>WorkflowActivity</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowActivity> getFinishModeWorkflowActivitys() throws RepositoryException {
        if (this.finishModeWorkflowActivitys == null) {
            this.finishModeWorkflowActivitys = getRelated(WorkflowActivity.class, "FinishModeWorkflowActivity");
        }
        return this.finishModeWorkflowActivitys;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowActivity</code> by the relation named <code>JoinWorkflowActivity</code>.
     * @return the list of <code>WorkflowActivity</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowActivity> getJoinWorkflowActivitys() throws RepositoryException {
        if (this.joinWorkflowActivitys == null) {
            this.joinWorkflowActivitys = getRelated(WorkflowActivity.class, "JoinWorkflowActivity");
        }
        return this.joinWorkflowActivitys;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowActivity</code> by the relation named <code>SplitWorkflowActivity</code>.
     * @return the list of <code>WorkflowActivity</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowActivity> getSplitWorkflowActivitys() throws RepositoryException {
        if (this.splitWorkflowActivitys == null) {
            this.splitWorkflowActivitys = getRelated(WorkflowActivity.class, "SplitWorkflowActivity");
        }
        return this.splitWorkflowActivitys;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowComplexTypeInfo</code> by the relation named <code>DataTypeWorkflowComplexTypeInfo</code>.
     * @return the list of <code>WorkflowComplexTypeInfo</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowComplexTypeInfo> getDataTypeWorkflowComplexTypeInfoes() throws RepositoryException {
        if (this.dataTypeWorkflowComplexTypeInfoes == null) {
            this.dataTypeWorkflowComplexTypeInfoes = getRelated(WorkflowComplexTypeInfo.class, "DataTypeWorkflowComplexTypeInfo");
        }
        return this.dataTypeWorkflowComplexTypeInfoes;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowDataField</code> by the relation named <code>DataTypeWorkflowDataField</code>.
     * @return the list of <code>WorkflowDataField</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowDataField> getDataTypeWorkflowDataFields() throws RepositoryException {
        if (this.dataTypeWorkflowDataFields == null) {
            this.dataTypeWorkflowDataFields = getRelated(WorkflowDataField.class, "DataTypeWorkflowDataField");
        }
        return this.dataTypeWorkflowDataFields;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowFormalParam</code> by the relation named <code>ModeWorkflowFormalParam</code>.
     * @return the list of <code>WorkflowFormalParam</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowFormalParam> getModeWorkflowFormalParams() throws RepositoryException {
        if (this.modeWorkflowFormalParams == null) {
            this.modeWorkflowFormalParams = getRelated(WorkflowFormalParam.class, "ModeWorkflowFormalParam");
        }
        return this.modeWorkflowFormalParams;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowFormalParam</code> by the relation named <code>DataTypeWorkflowFormalParam</code>.
     * @return the list of <code>WorkflowFormalParam</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowFormalParam> getDataTypeWorkflowFormalParams() throws RepositoryException {
        if (this.dataTypeWorkflowFormalParams == null) {
            this.dataTypeWorkflowFormalParams = getRelated(WorkflowFormalParam.class, "DataTypeWorkflowFormalParam");
        }
        return this.dataTypeWorkflowFormalParams;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowPackage</code> by the relation named <code>GraphConformanceWorkflowPackage</code>.
     * @return the list of <code>WorkflowPackage</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowPackage> getGraphConformanceWorkflowPackages() throws RepositoryException {
        if (this.graphConformanceWorkflowPackages == null) {
            this.graphConformanceWorkflowPackages = getRelated(WorkflowPackage.class, "GraphConformanceWorkflowPackage");
        }
        return this.graphConformanceWorkflowPackages;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowTransition</code> by the relation named <code>ConditionTypeWorkflowTransition</code>.
     * @return the list of <code>WorkflowTransition</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowTransition> getConditionTypeWorkflowTransitions() throws RepositoryException {
        if (this.conditionTypeWorkflowTransitions == null) {
            this.conditionTypeWorkflowTransitions = getRelated(WorkflowTransition.class, "ConditionTypeWorkflowTransition");
        }
        return this.conditionTypeWorkflowTransitions;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowTransition</code> by the relation named <code>LoopTypeWorkflowTransition</code>.
     * @return the list of <code>WorkflowTransition</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowTransition> getLoopTypeWorkflowTransitions() throws RepositoryException {
        if (this.loopTypeWorkflowTransitions == null) {
            this.loopTypeWorkflowTransitions = getRelated(WorkflowTransition.class, "LoopTypeWorkflowTransition");
        }
        return this.loopTypeWorkflowTransitions;
    }
    /**
     * Auto generated method that gets the related <code>WorkflowTypeDeclaration</code> by the relation named <code>DataTypeWorkflowTypeDeclaration</code>.
     * @return the list of <code>WorkflowTypeDeclaration</code>
     * @throws RepositoryException if an error occurs
     */
    public List<? extends WorkflowTypeDeclaration> getDataTypeWorkflowTypeDeclarations() throws RepositoryException {
        if (this.dataTypeWorkflowTypeDeclarations == null) {
            this.dataTypeWorkflowTypeDeclarations = getRelated(WorkflowTypeDeclaration.class, "DataTypeWorkflowTypeDeclaration");
        }
        return this.dataTypeWorkflowTypeDeclarations;
    }

    /**
     * Auto generated value setter.
     * @param enumerationType the enumerationType to set
    */
    public void setEnumerationType(EnumerationType enumerationType) {
        this.enumerationType = enumerationType;
    }
    /**
     * Auto generated value setter.
     * @param enumeration the enumeration to set
    */
    public void setEnumeration(Enumeration enumeration) {
        this.enumeration = enumeration;
    }
    /**
     * Auto generated value setter.
     * @param balanceTypeAccountBalanceHistorys the balanceTypeAccountBalanceHistorys to set
    */
    public void setBalanceTypeAccountBalanceHistorys(List<AccountBalanceHistory> balanceTypeAccountBalanceHistorys) {
        this.balanceTypeAccountBalanceHistorys = balanceTypeAccountBalanceHistorys;
    }
    /**
     * Auto generated value setter.
     * @param agreementTerms the agreementTerms to set
    */
    public void setAgreementTerms(List<AgreementTerm> agreementTerms) {
        this.agreementTerms = agreementTerms;
    }
    /**
     * Auto generated value setter.
     * @param privilegeContents the privilegeContents to set
    */
    public void setPrivilegeContents(List<Content> privilegeContents) {
        this.privilegeContents = privilegeContents;
    }
    /**
     * Auto generated value setter.
     * @param classificationContents the classificationContents to set
    */
    public void setClassificationContents(List<Content> classificationContents) {
        this.classificationContents = classificationContents;
    }
    /**
     * Auto generated value setter.
     * @param contentPurposeOperations the contentPurposeOperations to set
    */
    public void setContentPurposeOperations(List<ContentPurposeOperation> contentPurposeOperations) {
        this.contentPurposeOperations = contentPurposeOperations;
    }
    /**
     * Auto generated value setter.
     * @param salesChannelCustRequests the salesChannelCustRequests to set
    */
    public void setSalesChannelCustRequests(List<CustRequest> salesChannelCustRequests) {
        this.salesChannelCustRequests = salesChannelCustRequests;
    }
    /**
     * Auto generated value setter.
     * @param facilitys the facilitys to set
    */
    public void setFacilitys(List<Facility> facilitys) {
        this.facilitys = facilitys;
    }
    /**
     * Auto generated value setter.
     * @param typeFacilityLocations the typeFacilityLocations to set
    */
    public void setTypeFacilityLocations(List<FacilityLocation> typeFacilityLocations) {
        this.typeFacilityLocations = typeFacilityLocations;
    }
    /**
     * Auto generated value setter.
     * @param replenishFinAccountTypes the replenishFinAccountTypes to set
    */
    public void setReplenishFinAccountTypes(List<FinAccountType> replenishFinAccountTypes) {
        this.replenishFinAccountTypes = replenishFinAccountTypes;
    }
    /**
     * Auto generated value setter.
     * @param classFixedAssets the classFixedAssets to set
    */
    public void setClassFixedAssets(List<FixedAsset> classFixedAssets) {
        this.classFixedAssets = classFixedAssets;
    }
    /**
     * Auto generated value setter.
     * @param giftCardFulfillments the giftCardFulfillments to set
    */
    public void setGiftCardFulfillments(List<GiftCardFulfillment> giftCardFulfillments) {
        this.giftCardFulfillments = giftCardFulfillments;
    }
    /**
     * Auto generated value setter.
     * @param reasonInventoryItemDetails the reasonInventoryItemDetails to set
    */
    public void setReasonInventoryItemDetails(List<InventoryItemDetail> reasonInventoryItemDetails) {
        this.reasonInventoryItemDetails = reasonInventoryItemDetails;
    }
    /**
     * Auto generated value setter.
     * @param relationshipKeywordThesauruses the relationshipKeywordThesauruses to set
    */
    public void setRelationshipKeywordThesauruses(List<KeywordThesaurus> relationshipKeywordThesauruses) {
        this.relationshipKeywordThesauruses = relationshipKeywordThesauruses;
    }
    /**
     * Auto generated value setter.
     * @param oldValueLinkFulfillments the oldValueLinkFulfillments to set
    */
    public void setOldValueLinkFulfillments(List<OldValueLinkFulfillment> oldValueLinkFulfillments) {
        this.oldValueLinkFulfillments = oldValueLinkFulfillments;
    }
    /**
     * Auto generated value setter.
     * @param salesChannelOrderHeaders the salesChannelOrderHeaders to set
    */
    public void setSalesChannelOrderHeaders(List<OrderHeader> salesChannelOrderHeaders) {
        this.salesChannelOrderHeaders = salesChannelOrderHeaders;
    }
    /**
     * Auto generated value setter.
     * @param orderNotifications the orderNotifications to set
    */
    public void setOrderNotifications(List<OrderNotification> orderNotifications) {
        this.orderNotifications = orderNotifications;
    }
    /**
     * Auto generated value setter.
     * @param taxFormPartyAcctgPreferences the taxFormPartyAcctgPreferences to set
    */
    public void setTaxFormPartyAcctgPreferences(List<PartyAcctgPreference> taxFormPartyAcctgPreferences) {
        this.taxFormPartyAcctgPreferences = taxFormPartyAcctgPreferences;
    }
    /**
     * Auto generated value setter.
     * @param cogsPartyAcctgPreferences the cogsPartyAcctgPreferences to set
    */
    public void setCogsPartyAcctgPreferences(List<PartyAcctgPreference> cogsPartyAcctgPreferences) {
        this.cogsPartyAcctgPreferences = cogsPartyAcctgPreferences;
    }
    /**
     * Auto generated value setter.
     * @param invoiceSequencePartyAcctgPreferences the invoiceSequencePartyAcctgPreferences to set
    */
    public void setInvoiceSequencePartyAcctgPreferences(List<PartyAcctgPreference> invoiceSequencePartyAcctgPreferences) {
        this.invoiceSequencePartyAcctgPreferences = invoiceSequencePartyAcctgPreferences;
    }
    /**
     * Auto generated value setter.
     * @param quoteSequencePartyAcctgPreferences the quoteSequencePartyAcctgPreferences to set
    */
    public void setQuoteSequencePartyAcctgPreferences(List<PartyAcctgPreference> quoteSequencePartyAcctgPreferences) {
        this.quoteSequencePartyAcctgPreferences = quoteSequencePartyAcctgPreferences;
    }
    /**
     * Auto generated value setter.
     * @param orderSequencePartyAcctgPreferences the orderSequencePartyAcctgPreferences to set
    */
    public void setOrderSequencePartyAcctgPreferences(List<PartyAcctgPreference> orderSequencePartyAcctgPreferences) {
        this.orderSequencePartyAcctgPreferences = orderSequencePartyAcctgPreferences;
    }
    /**
     * Auto generated value setter.
     * @param costingMethodPartyAcctgPreferences the costingMethodPartyAcctgPreferences to set
    */
    public void setCostingMethodPartyAcctgPreferences(List<PartyAcctgPreference> costingMethodPartyAcctgPreferences) {
        this.costingMethodPartyAcctgPreferences = costingMethodPartyAcctgPreferences;
    }
    /**
     * Auto generated value setter.
     * @param partyContents the partyContents to set
    */
    public void setPartyContents(List<PartyContent> partyContents) {
        this.partyContents = partyContents;
    }
    /**
     * Auto generated value setter.
     * @param industryPartySupplementalDatas the industryPartySupplementalDatas to set
    */
    public void setIndustryPartySupplementalDatas(List<PartySupplementalData> industryPartySupplementalDatas) {
        this.industryPartySupplementalDatas = industryPartySupplementalDatas;
    }
    /**
     * Auto generated value setter.
     * @param ownershipPartySupplementalDatas the ownershipPartySupplementalDatas to set
    */
    public void setOwnershipPartySupplementalDatas(List<PartySupplementalData> ownershipPartySupplementalDatas) {
        this.ownershipPartySupplementalDatas = ownershipPartySupplementalDatas;
    }
    /**
     * Auto generated value setter.
     * @param serviceTypePaymentGatewayResponses the serviceTypePaymentGatewayResponses to set
    */
    public void setServiceTypePaymentGatewayResponses(List<PaymentGatewayResponse> serviceTypePaymentGatewayResponses) {
        this.serviceTypePaymentGatewayResponses = serviceTypePaymentGatewayResponses;
    }
    /**
     * Auto generated value setter.
     * @param tranCodePaymentGatewayResponses the tranCodePaymentGatewayResponses to set
    */
    public void setTranCodePaymentGatewayResponses(List<PaymentGatewayResponse> tranCodePaymentGatewayResponses) {
        this.tranCodePaymentGatewayResponses = tranCodePaymentGatewayResponses;
    }
    /**
     * Auto generated value setter.
     * @param employmentStatuspeople the employmentStatuspeople to set
    */
    public void setEmploymentStatuspeople(List<Person> employmentStatuspeople) {
        this.employmentStatuspeople = employmentStatuspeople;
    }
    /**
     * Auto generated value setter.
     * @param residenceStatuspeople the residenceStatuspeople to set
    */
    public void setResidenceStatuspeople(List<Person> residenceStatuspeople) {
        this.residenceStatuspeople = residenceStatuspeople;
    }
    /**
     * Auto generated value setter.
     * @param ratingProducts the ratingProducts to set
    */
    public void setRatingProducts(List<Product> ratingProducts) {
        this.ratingProducts = ratingProducts;
    }
    /**
     * Auto generated value setter.
     * @param requirementMethodProducts the requirementMethodProducts to set
    */
    public void setRequirementMethodProducts(List<Product> requirementMethodProducts) {
        this.requirementMethodProducts = requirementMethodProducts;
    }
    /**
     * Auto generated value setter.
     * @param linkTypeProductCategoryLinks the linkTypeProductCategoryLinks to set
    */
    public void setLinkTypeProductCategoryLinks(List<ProductCategoryLink> linkTypeProductCategoryLinks) {
        this.linkTypeProductCategoryLinks = linkTypeProductCategoryLinks;
    }
    /**
     * Auto generated value setter.
     * @param resplenishMethodProductFacilitys the resplenishMethodProductFacilitys to set
    */
    public void setResplenishMethodProductFacilitys(List<ProductFacility> resplenishMethodProductFacilitys) {
        this.resplenishMethodProductFacilitys = resplenishMethodProductFacilitys;
    }
    /**
     * Auto generated value setter.
     * @param productGeos the productGeos to set
    */
    public void setProductGeos(List<ProductGeo> productGeos) {
        this.productGeos = productGeos;
    }
    /**
     * Auto generated value setter.
     * @param inputParamProductPriceConds the inputParamProductPriceConds to set
    */
    public void setInputParamProductPriceConds(List<ProductPriceCond> inputParamProductPriceConds) {
        this.inputParamProductPriceConds = inputParamProductPriceConds;
    }
    /**
     * Auto generated value setter.
     * @param operatorProductPriceConds the operatorProductPriceConds to set
    */
    public void setOperatorProductPriceConds(List<ProductPriceCond> operatorProductPriceConds) {
        this.operatorProductPriceConds = operatorProductPriceConds;
    }
    /**
     * Auto generated value setter.
     * @param actionProductPromoActions the actionProductPromoActions to set
    */
    public void setActionProductPromoActions(List<ProductPromoAction> actionProductPromoActions) {
        this.actionProductPromoActions = actionProductPromoActions;
    }
    /**
     * Auto generated value setter.
     * @param applProductPromoCategorys the applProductPromoCategorys to set
    */
    public void setApplProductPromoCategorys(List<ProductPromoCategory> applProductPromoCategorys) {
        this.applProductPromoCategorys = applProductPromoCategorys;
    }
    /**
     * Auto generated value setter.
     * @param inputParamProductPromoConds the inputParamProductPromoConds to set
    */
    public void setInputParamProductPromoConds(List<ProductPromoCond> inputParamProductPromoConds) {
        this.inputParamProductPromoConds = inputParamProductPromoConds;
    }
    /**
     * Auto generated value setter.
     * @param operatorProductPromoConds the operatorProductPromoConds to set
    */
    public void setOperatorProductPromoConds(List<ProductPromoCond> operatorProductPromoConds) {
        this.operatorProductPromoConds = operatorProductPromoConds;
    }
    /**
     * Auto generated value setter.
     * @param applProductPromoProducts the applProductPromoProducts to set
    */
    public void setApplProductPromoProducts(List<ProductPromoProduct> applProductPromoProducts) {
        this.applProductPromoProducts = applProductPromoProducts;
    }
    /**
     * Auto generated value setter.
     * @param reserveOrderProductStores the reserveOrderProductStores to set
    */
    public void setReserveOrderProductStores(List<ProductStore> reserveOrderProductStores) {
        this.reserveOrderProductStores = reserveOrderProductStores;
    }
    /**
     * Auto generated value setter.
     * @param requirementMethodProductStores the requirementMethodProductStores to set
    */
    public void setRequirementMethodProductStores(List<ProductStore> requirementMethodProductStores) {
        this.requirementMethodProductStores = requirementMethodProductStores;
    }
    /**
     * Auto generated value setter.
     * @param defaultSalesChannelProductStores the defaultSalesChannelProductStores to set
    */
    public void setDefaultSalesChannelProductStores(List<ProductStore> defaultSalesChannelProductStores) {
        this.defaultSalesChannelProductStores = defaultSalesChannelProductStores;
    }
    /**
     * Auto generated value setter.
     * @param productStoreEmailSettings the productStoreEmailSettings to set
    */
    public void setProductStoreEmailSettings(List<ProductStoreEmailSetting> productStoreEmailSettings) {
        this.productStoreEmailSettings = productStoreEmailSettings;
    }
    /**
     * Auto generated value setter.
     * @param productStoreKeywordOvrds the productStoreKeywordOvrds to set
    */
    public void setProductStoreKeywordOvrds(List<ProductStoreKeywordOvrd> productStoreKeywordOvrds) {
        this.productStoreKeywordOvrds = productStoreKeywordOvrds;
    }
    /**
     * Auto generated value setter.
     * @param productStorePaymentSettings the productStorePaymentSettings to set
    */
    public void setProductStorePaymentSettings(List<ProductStorePaymentSetting> productStorePaymentSettings) {
        this.productStorePaymentSettings = productStorePaymentSettings;
    }
    /**
     * Auto generated value setter.
     * @param salesChannelQuotes the salesChannelQuotes to set
    */
    public void setSalesChannelQuotes(List<Quote> salesChannelQuotes) {
        this.salesChannelQuotes = salesChannelQuotes;
    }
    /**
     * Auto generated value setter.
     * @param typeSalesOpportunitys the typeSalesOpportunitys to set
    */
    public void setTypeSalesOpportunitys(List<SalesOpportunity> typeSalesOpportunitys) {
        this.typeSalesOpportunitys = typeSalesOpportunitys;
    }
    /**
     * Auto generated value setter.
     * @param testEntitys the testEntitys to set
    */
    public void setTestEntitys(List<TestEntity> testEntitys) {
        this.testEntitys = testEntitys;
    }
    /**
     * Auto generated value setter.
     * @param trackingCodeVisits the trackingCodeVisits to set
    */
    public void setTrackingCodeVisits(List<TrackingCodeVisit> trackingCodeVisits) {
        this.trackingCodeVisits = trackingCodeVisits;
    }
    /**
     * Auto generated value setter.
     * @param viewPreferences the viewPreferences to set
    */
    public void setViewPreferences(List<ViewPreference> viewPreferences) {
        this.viewPreferences = viewPreferences;
    }
    /**
     * Auto generated value setter.
     * @param scopeWorkEfforts the scopeWorkEfforts to set
    */
    public void setScopeWorkEfforts(List<WorkEffort> scopeWorkEfforts) {
        this.scopeWorkEfforts = scopeWorkEfforts;
    }
    /**
     * Auto generated value setter.
     * @param expectationWorkEffortPartyAssignments the expectationWorkEffortPartyAssignments to set
    */
    public void setExpectationWorkEffortPartyAssignments(List<WorkEffortPartyAssignment> expectationWorkEffortPartyAssignments) {
        this.expectationWorkEffortPartyAssignments = expectationWorkEffortPartyAssignments;
    }
    /**
     * Auto generated value setter.
     * @param startModeWorkflowActivitys the startModeWorkflowActivitys to set
    */
    public void setStartModeWorkflowActivitys(List<WorkflowActivity> startModeWorkflowActivitys) {
        this.startModeWorkflowActivitys = startModeWorkflowActivitys;
    }
    /**
     * Auto generated value setter.
     * @param finishModeWorkflowActivitys the finishModeWorkflowActivitys to set
    */
    public void setFinishModeWorkflowActivitys(List<WorkflowActivity> finishModeWorkflowActivitys) {
        this.finishModeWorkflowActivitys = finishModeWorkflowActivitys;
    }
    /**
     * Auto generated value setter.
     * @param joinWorkflowActivitys the joinWorkflowActivitys to set
    */
    public void setJoinWorkflowActivitys(List<WorkflowActivity> joinWorkflowActivitys) {
        this.joinWorkflowActivitys = joinWorkflowActivitys;
    }
    /**
     * Auto generated value setter.
     * @param splitWorkflowActivitys the splitWorkflowActivitys to set
    */
    public void setSplitWorkflowActivitys(List<WorkflowActivity> splitWorkflowActivitys) {
        this.splitWorkflowActivitys = splitWorkflowActivitys;
    }
    /**
     * Auto generated value setter.
     * @param dataTypeWorkflowComplexTypeInfoes the dataTypeWorkflowComplexTypeInfoes to set
    */
    public void setDataTypeWorkflowComplexTypeInfoes(List<WorkflowComplexTypeInfo> dataTypeWorkflowComplexTypeInfoes) {
        this.dataTypeWorkflowComplexTypeInfoes = dataTypeWorkflowComplexTypeInfoes;
    }
    /**
     * Auto generated value setter.
     * @param dataTypeWorkflowDataFields the dataTypeWorkflowDataFields to set
    */
    public void setDataTypeWorkflowDataFields(List<WorkflowDataField> dataTypeWorkflowDataFields) {
        this.dataTypeWorkflowDataFields = dataTypeWorkflowDataFields;
    }
    /**
     * Auto generated value setter.
     * @param modeWorkflowFormalParams the modeWorkflowFormalParams to set
    */
    public void setModeWorkflowFormalParams(List<WorkflowFormalParam> modeWorkflowFormalParams) {
        this.modeWorkflowFormalParams = modeWorkflowFormalParams;
    }
    /**
     * Auto generated value setter.
     * @param dataTypeWorkflowFormalParams the dataTypeWorkflowFormalParams to set
    */
    public void setDataTypeWorkflowFormalParams(List<WorkflowFormalParam> dataTypeWorkflowFormalParams) {
        this.dataTypeWorkflowFormalParams = dataTypeWorkflowFormalParams;
    }
    /**
     * Auto generated value setter.
     * @param graphConformanceWorkflowPackages the graphConformanceWorkflowPackages to set
    */
    public void setGraphConformanceWorkflowPackages(List<WorkflowPackage> graphConformanceWorkflowPackages) {
        this.graphConformanceWorkflowPackages = graphConformanceWorkflowPackages;
    }
    /**
     * Auto generated value setter.
     * @param conditionTypeWorkflowTransitions the conditionTypeWorkflowTransitions to set
    */
    public void setConditionTypeWorkflowTransitions(List<WorkflowTransition> conditionTypeWorkflowTransitions) {
        this.conditionTypeWorkflowTransitions = conditionTypeWorkflowTransitions;
    }
    /**
     * Auto generated value setter.
     * @param loopTypeWorkflowTransitions the loopTypeWorkflowTransitions to set
    */
    public void setLoopTypeWorkflowTransitions(List<WorkflowTransition> loopTypeWorkflowTransitions) {
        this.loopTypeWorkflowTransitions = loopTypeWorkflowTransitions;
    }
    /**
     * Auto generated value setter.
     * @param dataTypeWorkflowTypeDeclarations the dataTypeWorkflowTypeDeclarations to set
    */
    public void setDataTypeWorkflowTypeDeclarations(List<WorkflowTypeDeclaration> dataTypeWorkflowTypeDeclarations) {
        this.dataTypeWorkflowTypeDeclarations = dataTypeWorkflowTypeDeclarations;
    }

    /**
     * Auto generated method that add item to collection.
     */
    public void addContentPurposeOperation(ContentPurposeOperation contentPurposeOperation) {
        if (this.contentPurposeOperations == null) {
            this.contentPurposeOperations = new ArrayList<ContentPurposeOperation>();
        }
        this.contentPurposeOperations.add(contentPurposeOperation);
    }
    /**
     * Auto generated method that remove item from collection.
     */
    public void removeContentPurposeOperation(ContentPurposeOperation contentPurposeOperation) {
        if (this.contentPurposeOperations == null) {
            return;
        }
        this.contentPurposeOperations.remove(contentPurposeOperation);
    }
    /**
     * Auto generated method that clear items from collection.
     */
    public void clearContentPurposeOperation() {
        if (this.contentPurposeOperations == null) {
            return;
        }
        this.contentPurposeOperations.clear();
    }
    /**
     * Auto generated method that add item to collection.
     */
    public void addProductStoreEmailSetting(ProductStoreEmailSetting productStoreEmailSetting) {
        if (this.productStoreEmailSettings == null) {
            this.productStoreEmailSettings = new ArrayList<ProductStoreEmailSetting>();
        }
        this.productStoreEmailSettings.add(productStoreEmailSetting);
    }
    /**
     * Auto generated method that remove item from collection.
     */
    public void removeProductStoreEmailSetting(ProductStoreEmailSetting productStoreEmailSetting) {
        if (this.productStoreEmailSettings == null) {
            return;
        }
        this.productStoreEmailSettings.remove(productStoreEmailSetting);
    }
    /**
     * Auto generated method that clear items from collection.
     */
    public void clearProductStoreEmailSetting() {
        if (this.productStoreEmailSettings == null) {
            return;
        }
        this.productStoreEmailSettings.clear();
    }
    /**
     * Auto generated method that add item to collection.
     */
    public void addProductStorePaymentSetting(ProductStorePaymentSetting productStorePaymentSetting) {
        if (this.productStorePaymentSettings == null) {
            this.productStorePaymentSettings = new ArrayList<ProductStorePaymentSetting>();
        }
        this.productStorePaymentSettings.add(productStorePaymentSetting);
    }
    /**
     * Auto generated method that remove item from collection.
     */
    public void removeProductStorePaymentSetting(ProductStorePaymentSetting productStorePaymentSetting) {
        if (this.productStorePaymentSettings == null) {
            return;
        }
        this.productStorePaymentSettings.remove(productStorePaymentSetting);
    }
    /**
     * Auto generated method that clear items from collection.
     */
    public void clearProductStorePaymentSetting() {
        if (this.productStorePaymentSettings == null) {
            return;
        }
        this.productStorePaymentSettings.clear();
    }

    /** {@inheritDoc} */
    @Override
    public void fromMap(Map<String, Object> mapValue) {
        preInit();
        setEnumId((String) mapValue.get("enumId"));
        setEnumTypeId((String) mapValue.get("enumTypeId"));
        setEnumCode((String) mapValue.get("enumCode"));
        setSequenceId((String) mapValue.get("sequenceId"));
        setDescription((String) mapValue.get("description"));
        setLastUpdatedStamp((Timestamp) mapValue.get("lastUpdatedStamp"));
        setLastUpdatedTxStamp((Timestamp) mapValue.get("lastUpdatedTxStamp"));
        setCreatedStamp((Timestamp) mapValue.get("createdStamp"));
        setCreatedTxStamp((Timestamp) mapValue.get("createdTxStamp"));
        setParentEnumId((String) mapValue.get("parentEnumId"));
        postInit();
    }

    /** {@inheritDoc} */
    @Override
    public Map<String, Object> toMap() {
        Map<String, Object> mapValue = new FastMap<String, Object>();
        mapValue.put("enumId", getEnumId());
        mapValue.put("enumTypeId", getEnumTypeId());
        mapValue.put("enumCode", getEnumCode());
        mapValue.put("sequenceId", getSequenceId());
        mapValue.put("description", getDescription());
        mapValue.put("lastUpdatedStamp", getLastUpdatedStamp());
        mapValue.put("lastUpdatedTxStamp", getLastUpdatedTxStamp());
        mapValue.put("createdStamp", getCreatedStamp());
        mapValue.put("createdTxStamp", getCreatedTxStamp());
        mapValue.put("parentEnumId", getParentEnumId());
        return mapValue;
    }


}
